sonar.projectKey=laravel-ci-sonar
sonar.projectName=Laravel CI Sonar
sonar.sources=app
sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=vendor/**,storage/**,bootstrap/**
